/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array.insert.shift;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test void test1InsertShiftArray(){
        Library sut= new Library();
        int [] arr = {2,4,6,-8};
        int [] result =sut.insertShiftArray(arr,5);
        int [] expectedValue={2,4,5,6,-8};
        Assertions.assertArrayEquals(expectedValue,result);

}
    @Test void test2InsertShiftArray(){
        Library sut= new Library();
        int [] arr = {42,8,15,23,42};
        int [] result =sut.insertShiftArray(arr,16);
        System.out.println(result);
        int [] expectedValue={42,8,15,16,23,42};
        Assertions.assertArrayEquals(expectedValue,result);
    }


}
