/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array.binary.search;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test public void testBinarySearch1(){
        Library sut= new Library();
        int[] arr={4, 8, 15, 16, 23, 42};
        int result=sut.BinarySearch(arr,15);
        Assertions.assertEquals(2,result);
    }
    @Test public void testBinarySearch2(){
        Library sut= new Library();
        int[] arr={-131, -82, 0, 27, 42, 68, 179};
        int result=sut.BinarySearch(arr,42);
        Assertions.assertEquals(4,result);
    }
    @Test public void testBinarySearch3(){
        Library sut= new Library();
        int[] arr={11, 22, 33, 44, 55, 66, 77};
        int result=sut.BinarySearch(arr,90);
        Assertions.assertEquals(-1,result);
    }
    @Test public void testBinarySearch4(){
        Library sut= new Library();
        int[] arr={1, 2, 3, 5, 6, 7};
        int result=sut.BinarySearch(arr,4);
        Assertions.assertEquals(-1,result);
    }
}
