/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array.binary.search;

public class Library {
    public static int BinarySearch(int[] arr, int val) {
        int low = 0;
        int high = arr.length - 1;
        int index = -1;

        while (low <= high) {
            int placement = low + (high - low) / 2;

            if (arr[placement] < val) {
                low = placement + 1;
            } else if (arr[placement] == val) {
                index = placement;
                break;
            } else if(arr[placement] > val) {
                high = placement - 1;
            }

        }

        return index;
    }
}
